version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db

  client:
    build:
      context: ./client
    container_name: client
    image: iqbalcodes6602/thinkshare-client:latest
    ports:
      - "80"
    environment:
      - REACT_APP_BACKEND_URL=/api
    depends_on:
      - server

  server:
    build:
      context: ./server
    container_name: server
    image: iqbalcodes6602/thinkshare-server:latest
    ports:
      - "5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - PORT=5000
    depends_on:
      - mongo

  proxy:
    build:
      context: ./proxy
    container_name: proxy
    image: iqbalcodes6602/thinkshare-proxy:latest
    ports:
      - "80:80"
    depends_on:
      - client
      - server

volumes:
  mongo_data:
